spring:
  application:
    name: auth-service

logging:
  level:
    org.springframework: info
    io.github.resilience4j: debug

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics
          - prometheus